export const SAVE_DAILY_EXPENSE = 'SAVE_DAILY_EXPENSE';
export const SAVE_TO_DATABASE = 'SAVE_TO_DATABASE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const HIGHLIGHT_EXPENSE = 'HIGHLIGHT_EXPENSE';
export const CLEAR_EXPENSE = 'CLEAR_EXPENSE';
export const CLEAR_DATABASE = 'CLEAR_DATABASE';
export const SAVE_TOTAL_AMOUNT = 'SAVE_TOTAL_AMOUNT';
export const CLEAR_TOTAL_AMOUNT = 'CLEAR_TOTAL_AMOUNT';
